name: Check links

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout valkey-doc
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
    - name: Check links
      run: |
        ./utils/check-links.pl
